### ISSUE TITLE
SEO concern

### ISSUE THREAD

**Issue by JianGuo222** [kriasoft/react-static-boilerplate#101]
Hi,

I've created an app using this template. 90% of the content is populated by calling Web APIs from client side. Will google bot be able to crawl those client side async-ly generated content?

Thanks,

**Comment by koistya** [comment]
@JianGuo222 Google crawls dynamically generated websites like this one without any issues, what you can do though is to add one more build step that generates [sitemap.xml](http://www.sitemaps.org/protocol.html). Register your web app in Google Webmaster Tools that helps to monitor and tweak how the site is being indexed by Google. The build step for generating a source map may look something like this:

```js
tasks.set('sitemap', () => {
  const routes = require('./routes.json');
  const sitemap = routes.map(x => ....);
  const sitemapXml = /* serialize sitemap object */;
  fs.saveFileSynx('public/sitemap.xml', sitemapXml, 'utf-8');
});
```

A [pull request](https://help.github.com/articles/using-pull-requests/) with this feature is welcome!

**Comment by koistya** [comment]
@JianGuo222 just have added `sitemap` build step into `run.js`. Check it out. Now you can add more logic into this function to generate more URLs based on the result from your REST API service.
