### ISSUE TITLE
Get error log

### ISSUE THREAD

**Issue by jdelafon** [kriasoft/react-static-boilerplate#109]
When I have an error in my code, I get redirected to the "Error" page, which tells me nothing about the error but "something went wrong". Neither does the console. Neither does eslint. How am I supposed to know what kind of error occurred ? Any undocumented debug mode ?

Even worse, it shows no error as long as I don't reload the page manually ("webpack: bundle is now VALID"), so I don't even know there is an error.

Simplest reproducible example: paste this anywhere:

    undefined.length;

It should throw immediately on BrowserSync reload, and log "undefined has no attribute 'length'", either on the Error page or in the console - or both.

**Comment by koistya** [comment]
@jdelafon good catch! Do you think printing errors to the console should suffice? See e76dbf9.

![image](https://cloud.githubusercontent.com/assets/197134/16807033/a411e140-491f-11e6-8c85-8b65d4eaac0e.png)

Another approach is not to catch errors inside `core/router.js` in development mode (`process.env.NODE_ENV !== 'production'`). A PR with this fix would be welcome!

**Comment by jdelafon** [comment]
Good ! It helps a lot already.
I don't know what the usual approach is, but actually I'd prefer not being redirected at all on error in dev mode, because you can see which component could not be loaded due to an error (since it will be missing, but the parents get mounted anyway).

**Comment by koistya** [comment]
@jdelafon yeah, agreed, it would be better just to show the error message right away. Currently errors are catched inside main.js/render() method and redirect to `/error` page is handled inside the `core/router.js/resolve()` method, FYI.
