### ISSUE TITLE
build/app.node.js: 'import' and 'export' may only appear at the top level (342:2)

### ISSUE THREAD

**Issue by daniula** [kriasoft/react-static-boilerplate#110]
I wanted to add Redux to fetch and store some data from API. However build scripts are failing on imports in `configureStore.js` file:

```
import { createStore, applyMiddleware } from 'redux'
import thunkMiddleware from 'redux-thunk'
import createLogger from 'redux-logger'
```

**Comment by koistya** [comment]
Either move your `configureStore.js` file into the `core` (core framework) folder. Or, alternatively, add it to this list in [`webpack.config.js#L85-90`](https://github.com/kriasoft/react-static-boilerplate/blob/c97c62c/webpack.config.js#L85-L90).

A pull request (PR) with troubleshooting section in docs or README file is welcome!

**Comment by koistya** [comment]
@daniula also, if you think this boilerplate should come with `redux-thunk` and `redux-logger` by default, feel free to send a PR as well.
