### ISSUE TITLE
Run React-static-boilerplate in cloud9

### ISSUE THREAD

**Issue by Ruffeng** [kriasoft/react-static-boilerplate#117]
Once I've upgraded NodeJs on a cloud9 server, everything is running and working.
When I'm running the server with : 
`run node` Is working well. However, cloud 9 needs to specify the HOST and PORT with its specials vars $IP and $PORT.

this doesn't work:
`node run --host $IP -p $PORT`

How or what do I have to do to make it work?

**Comment by koistya** [comment]
@Ruffeng nice use case! Setting this port inside the `run.js/tasks.set('start', ...)`  function, for example:

```js
bs.init({
  server: {
    baseDir: 'public',
    middleware: [...]
  }
}, resolve);
```

will become:

```js
bs.init({
  server: {
    port: process.env.PORT,        // <= explicitely set the port (default is 3000)
    baseDir: 'public',
    middleware: [...]
  }
}, resolve);
```

`bs.init(..)` launches a new [Browsersync](https://browsersync.io/) (dev server). Here is the full list of its options:

https://browsersync.io/docs/options

**Comment by Ruffeng** [comment]
@koistya good answer!! However it still stuck with the same problem. Checking the options from browsersync I set up to the host option. 

```
...
// code
bs.init({
          server: {
            host: process.env.IP,
            port: process.env.PORT,        // <= explicitely set the port (default is 3000)
            baseDir: 'public'
            ....
// More code

```
I've been checking through internet trying to solve it but I cannot work out.

Thanks in advance!

**Comment by koistya** [comment]
I just pushed e059b92. Please, let me know if it doesn't fix the issue.

**Comment by Ruffeng** [comment]
Hi @koistya, it works perfectly!
Thank you so much!

If I can help with something don't hesitate to contact me.

**Comment by koistya** [comment]
@Ruffeng, always welcome! If you can help me to tweak CSS on the error page a little, that would be awesome! Here https://github.com/kriasoft/react-static-boilerplate/issues/97

**Comment by Ruffeng** [comment]
I'll try it!
