### ISSUE TITLE
public/index.html shows blank page after build

### ISSUE THREAD

**Issue by inaki** [kriasoft/react-static-boilerplate#136]
Hi, 

I just start using *react-static-boilerplate* and it works pretty fine, but. My problem is that when I run 'npm run build' everything works fine until I go to the **'public/index.html'** that shows a **blank page** in my browser. I just start a new project with yo, run the server and it works fine, run 'npm run build' and again the same problem. 

node: 6.3.1
npm: 3.10.3

BTW, awesome react starter.

**Comment by koistya** [comment]
Why don't you launch your website by running `npm start` (same as `node run` or `node run start`)? It seems like when you launch `public/index.html` directly, it may not download the main.js file. Check Netwrok Tap in Chrome Dev Tools.

**Comment by inaki** [comment]
Thanks @koistya, it is working now.

**Comment by VishalChauha** [comment]
Try to put "main":"index.js" in package.json file That solved my problem.

  ```
"main": "index.js",

  "scripts": {
    ...
  },
```

Happy to help.

**Comment by khanna2005m** [comment]
Hi,

I just start using react and it works fine, but. My problem is that when I run 'npm run build' everything works fine until I go to the **'build/index.html'** that shows a **blank page** in my browser.
