### ISSUE TITLE
Where exactly are the background colours for both header and footer being set?

### ISSUE THREAD

**Issue by TheoMer** [kriasoft/react-static-boilerplate#137]
Either old age has visited me early or I'm completely missing something here, but for the life of me I can't locate where the header (blue) and footer (grey) background colours are being set for the template. 

I've looked in both `components/layout` and `public/index.html`, but can't see it specified. 

What am I overlooking?

**Comment by TheoMer** [comment]
In `react-starter-kit` components/header and components/footer both have css files documenting their background colours, whilst in `react-static-boilerplate` we have components/footer and components/layout, which has references to the header, both of which have no css files pertinent to either header or footer.

And why in `react-static-boilerplate` is components/Footer specified as its own folder, whilst Header.(.css | .js) are specified within component/Layout?

**Comment by koistya** [comment]
These colors come from Material Design Lite (MDL). For example, if you open `components/Footer/Footer.js`, you will see `mdl-mini-footer` CSS class specified on the footer container element. This class name comes from `material.min.css` file referenced in `webpack.config.js/entry`. You can remove this 3rd party `.css` file and write your own styles similar to how it's done in `react-starter-kit`, e.g. `Footer.js` + `Footer.css`. Does this help?

**Comment by jolive1993** [comment]
Can you go into more detail about how to go about this? I would like to use MDL and NOT embed the styles in modules (doesn't work with the MDL js), but react-mdl is a terrible, completely non-extensible package that doesn't even allow me to change colors. When I try to modify the entry point webpack can't find any files I tell it too look for.
