### ISSUE TITLE
Accessing parameters in a URL

### ISSUE THREAD

**Issue by emmerich** [kriasoft/react-static-boilerplate#138]
I have a route, taken from routes.json,
```
{
    "path": "/tasks/:status(pending|completed)?",
    "page": "./pages/tasks/list"
}
```

When the page loads, how do I access the value of `status` in my React component? I have access to `this.props.route` but it's not in there.

**Comment by emmerich** [comment]
Well, I fixed the issue by changing `router.js` to pass the params. Line 79 of `router.js` becomes:

```
return route.load().then(Page => <Page route={route} routeParams={params} error={context.error} />);
```

and I can access via `routeParams`. Want me to open a pull request?

**Comment by koistya** [comment]
Alternatively, `route={{ ...route, params }}`. A pull request is welcome!
