### ISSUE TITLE
Error messages are less helpful now

### ISSUE THREAD

**Issue by AndroidDoctorr** [kriasoft/react-static-boilerplate#140]
Error messages in the old version used to point to the exact line that was causing the problem. For example, this worked in the old version:

`<div className="alert alert-danger vcAlert" id="endMasquerade" style={{ display: "none" }}>`
    `Exploring with Masquerade session.`
`<Link to={ "/assignments/" + oldSessionId } title="Return to Old Session" alt="Return to Old Session">`
              `<span>  Return to old session</span>`
            `</Link>`
          `</div>`

but now there's an error and the message is
"ReactCompositeComponent.js:758 Uncaught (in promise) TypeError: Cannot read property '_currentElement' of null(…)", 
and it doesn't point to the problematic line in my code, so I can't tell what the problem is.
Is this a bug or was error reporting changed on purpose? Either way, is there any way it can change back? I can't track down any of my bugs.

**Comment by UXDart** [comment]
I have the same problem... is there anyway to fix that? and get the line or some info about the error...? TIA
