### ISSUE TITLE
Publishing to S3 produces Error 404: NoSuchKey

### ISSUE THREAD

**Issue by AndroidDoctorr** [kriasoft/react-static-boilerplate#141]
With the new boilerplate (starting fresh), when I publish to S3, it works so long as I navigate using the links in the navbar. E.g. when I click on "About", it goes to the about page. When I then refresh the page (or type in the address with "/about" manually), I get this:

> 404 Not Found
> 
> Code: NoSuchKey
> Message: The specified key does not exist.
> Key: about
> RequestId: BF54147FF3BC0476
> HostId: /sfe4HiXv17iXdgdJkR/VicWupccv6xP81STSaxtFK1bJsCI3aW/ZkdNMWM6ogDnC22adzBxEhM=

When running on localhost, however, it works fine.
Could this have something to do with the new router.js?

**Comment by koistya** [comment]
I think you need to configure rewrites, so that all the unknown web requested are routed to index.html by Amazon S3:

http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
https://kkob.us/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/

**Comment by AndroidDoctorr** [comment]
That helped us figure it out, looks like it was a cache issue. Thank you!!!

**Comment by AndreiMotinga** [comment]
in my case, I had to specify index.html in both  `Index document` and `error document` on S3 Static website hosting properties.

**Comment by axellejamous** [comment]
@AndreiMotinga bless you

**Comment by aswin2772** [comment]
@AndreiMotinga  Thanks bro...

**Comment by Dev-Dipesh** [comment]
@AndreiMotinga 
That gets you most of the way there. If you inspect the requests, you’ll find that when the error document is being hit, you don’t get a 200 status code — which means that search engine crawlers will assume that the link is broken. If that’s okay for you, it isn’t a problem. 🙂
_(Originally mentioned by **Keita Kobayashi** on this [link](https://keita.blog/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/))_

**Comment by coalaroot** [comment]
@AndreiMotinga Thanks <3

**Comment by skeezus** [comment]
Adding a bit to @koistya because Keita pushes you towards her B solution when A might work for your project. All you need to do is add something like the following to the config in S3 -> Properties -> Static Website Hosting config.

```
<RoutingRules>
    <RoutingRule>
        <Condition>
            <HttpErrorCodeReturnedEquals>403</HttpErrorCodeReturnedEquals>
        </Condition>
        <Redirect>
            <HostName>host_name</HostName>
            <ReplaceKeyPrefixWith>#/</ReplaceKeyPrefixWith>
        </Redirect>
    </RoutingRule>
</RoutingRules>
```
src: your-bucket-endpoint-from-static-website-hosting-options

**Comment by JimmyAnthony** [comment]
Tienes que usar el "Endpoint" que provee AWS.
Lo encuentras en : Static website hosting.

You have to use the "Endpoint" that AWS provides.
You can find it at: Static website hosting.

**Comment by chandresh** [comment]
@AndroidDoctorr

> That helped us figure it out, looks like it was a cache issue. Thank you!!!

How did you solve the issue? I think I am also facing an issue related to cache.

**Comment by Gohchi** [comment]
> in my case, I had to specify index.html in both `Index document` and `error document` on S3 Static website hosting properties.

Thanks a lot!!!

**Comment by hyungmoklee** [comment]
> in my case, I had to specify index.html in both `Index document` and `error document` on S3 Static website hosting properties.

Thanks!

**Comment by rahmanimran** [comment]
> in my case, I had to specify index.html in both `Index document` and `error document` on S3 Static website hosting properties.

thanks a lot....life saver

**Comment by agarhy** [comment]
In CloudFront distribution Origins you need to use the S3 website URL including the region namespace as follow
"sub.myDomain.com.**s3-website-eu-east-1**.amazonaws.com"
referring to global S3 bucket URL from CF distribution won't work with paths properly 
e.g. "sub.myDomain.com.s3.amazonaws.com"

**Comment by Rock5r** [comment]
> help
