### ISSUE TITLE
Need a support to Sass/Scss module

### ISSUE THREAD

**Issue by smartlaksh** [kriasoft/react-static-boilerplate#142]
I wanted to use sass instead of plain css in the react-static-boilerplate project, is this possible already or it needs to be implemented?

**Comment by octagonal** [comment]
You can use the [postcss/postcss-scss](https://github.com/postcss/postcss-scss) plugin if you want to use SCSS alongside CSS. This will transform those stylesheets into something PostCSS can understand. 

If you wish, you can fully emulate SCSS or just pick and choose the features you want by using any number of [plugins](https://github.com/postcss/postcss#plugins). Have a look at [this article](https://pawelgrzybek.com/from-sass-to-postcss/) for further information.

**Comment by koistya** [comment]
In my practice, using plain CSS via PostCSS /w plugins, eliminates the need of Sass/SCSS/LESS. If you have some logic or computations in you CSS styles, it might be a better idea to move that into JavaScript code inside your React components - a more natural place for that stuff. If you still need to enable Sass, it should be easy to do, just follow this instruction from docs:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/how-to-use-sass.md

Please, let us know if you still have any issues. Will close this one for now.

**Comment by mamatopian** [comment]
Hey Guys. This is very confusing for me, where should I put step3? https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/how-to-use-sass.md#step-3
