### ISSUE TITLE
CSSTransitionGroup and routes

### ISSUE THREAD

**Issue by josephdburdick** [kriasoft/react-static-boilerplate#145]
Hi, thanks very much for this boilerplate, I'm enjoying it thoroughly. 

I'm trying to wrap around how I can wrap the routes around CSSTransitionGroup so I can achieve transitions between routes. I'm referring to [these docs](https://facebook.github.io/react/docs/animation.html#getting-started) but I don't see anything remotely similar to that in router or route-loader. Any ideas?

**Comment by frenzzy** [comment]
Maybe this example can help you: https://github.com/kriasoft/universal-router/issues/15#issuecomment-222808233

**Comment by josephdburdick** [comment]
Thanks @frenzzy  I understand that I'm supposed to wrap the elements with CSSTransitionGroup but where in *this* boilerplate is that appropriate? There's no "list" of routes anywhere because they're all dynamically generated.

**Comment by koistya** [comment]
@josephdburdick for example, you can put `<React.addons.CSSTransitionGroup>` inside your `components/Layout/Layout.js` component alongside with the corresponding CSS styles in `components/Layout.css`, that should do the trick I believe.

**Comment by josephdburdick** [comment]
@koistya That's exactly what I was looking for, thanks for the support!

**Comment by stinoga** [comment]
@josephdburdick Did you get CSSTransitionGroup to work? I tried what's below, and can only get the enter/leave classes to apply when I click on the current active page in the header.

```jsx
<div className="mdl-layout mdl-js-layout" ref={node => (this.root = node)}>
  <div className="mdl-layout__inner-container">
    <Header />
    <ReactCSSTransitionGroup
      component="div"
      className="container"
      transitionName={{
        enter: s.enter,
        leave: s.leave
      }}
      transitionEnterTimeout={9000}
      transitionLeaveTimeout={9000}
    >
      <main className="mdl-layout__content" key={Math.random()}>
        <div key={Math.random()} {...this.props} className={cx(s.content, this.props.className)} />
        <Footer key={Math.random()} />
      </main>
    </ReactCSSTransitionGroup>
  </div>
</div>
```
