### ISSUE TITLE
Note to noobs - latest commit appears to have broken things (21/09/2016 ;-)

### ISSUE THREAD

**Issue by johnmw** [kriasoft/react-static-boilerplate#149]
Just a note to other newbies (21 Sept 2016):

You will get the following error on npm start:

ERROR in ./core/router.js
Module build failed: SyntaxError: "url" is read-only

Remove the lines in this last change and things should work again:

https://github.com/kriasoft/react-static-boilerplate/commit/cbfe71cbd50f08f614eedfca60933db5d8adb78f

**Comment by koistya** [comment]
Thanks for the report! Fixed in ab5be06.
