### ISSUE TITLE
ReactCSSTransitionGroup when changing path

### ISSUE THREAD

**Issue by stinoga** [kriasoft/react-static-boilerplate#168]
I can't get transitions between pages working. I've tried basing my code off of the universal router example [here](https://github.com/kriasoft/universal-router/issues/15#issuecomment-222808233), but it doesn't work. I'm passing a unique `path` prop to use as the unique transition key for `ReactCSSTransitionGroup` to use.

I've also tried setting `ReactCSSTransitionGroup` at every level in the `Layout.js` file, and none have worked. What am I missing?

Here is my latest `Layout.js` code:

```jsx
render() {
  const {
    path,
    children
  } = this.props;

  return (
    <ReactCSSTransitionGroup
      component="div"
      className="container"
      transitionName={{
        enter: s.enter,
        leave: s.leave
      }}
      transitionEnterTimeout={9000}
      transitionLeaveTimeout={9000}
    >
      <div className="mdl-layout mdl-js-layout" key={path} ref={node => (this.root = node)}>
        <div className="mdl-layout__inner-container">
          <Header />
          <main className="mdl-layout__content">
            <div className={cx(s.content, this.props.className)}>
              {children}
            </div>
            <Footer />
          </main>
        </div>
      </div>
    </ReactCSSTransitionGroup>
  );
}
```

**Comment by frenzzy** [comment]
Are you sure path is changing? Do you see two `mdl-layout mdl-js-layout` elements in the dom for 9000 ms after page change? Maybe you forgot to add transition css.

**Comment by stinoga** [comment]
@frenzzy I see the path changing, yes. I don't see the `mdl-layout mdl-js-layout` showing duplicated in the dom for 9000ms like I would assume. It seems like everything inside the `container` div gets reloaded.

Also, I do have transition css. I import the `Layout.css` file as `s`, which is users in the `transitionName`. I've tested the classes with another instance of `ReactCSSTransitionGroup` and they work fine.

**Comment by stinoga** [comment]
@frenzzy Yes, it seems like everything is reloading, including the navigation in the `Header` component. Is this intended? Seems like it wouldn't allow for things like animation if that is the case.

The other thing I noticed is that the animation works when you navigate to the same page you are currently on (if you set the key to a random number so it changes), because the entire dom isn't rerendered.

**Comment by stinoga** [comment]
@frenzzy @koistya any direction on this? I'd love to see a working example of `ReactCSSTransitionGroup` and changing paths. I'd gladly add it to the documentation once I get it working as well. Thanks!

**Comment by frenzzy** [comment]
see https://github.com/kriasoft/react-starter-kit/pull/959

**Comment by stinoga** [comment]
@frenzzy Worked great! I was also able to get it to work in the [react-static-boilerplate](https://github.com/kriasoft/react-static-boilerplate) repo as well.

**Comment by zaneriley** [comment]
@stinoga Do you mind sharing your solution? I don't think I understand the change by moving the `<Layout />` component.
