### ISSUE TITLE
Routes.json 

### ISSUE THREAD

**Issue by harshjulka** [kriasoft/react-static-boilerplate#178]
I have used react-static-boilerplate for scaffolding my app and I am confused with below.
Can anyone please explain how we are fetching articles.json directly without using ajax call or something else.

 {
    "path": "/",
    "page": "./pages/home",
    "chunk": "main",
    "data": {
      

> "articles": "GET https://gist.githubusercontent.com/koistya/a32919e847531320675764e7308b796a/raw/articles.json"

    }
  },

I am confused with above step please explain so that i can proceed with react forward.

**Comment by justin22** [comment]
@harshjulka fetch is done in `core/router.js` file.

**Comment by harshjulka** [comment]
@justin22  Thanks! for info.
