### ISSUE TITLE
No jshint ECMAScript version option in .jshintrc project file

### ISSUE THREAD

**Issue by tomharvey** [kriasoft/react-static-boilerplate#179]
I'm using jshint for listing in my editor. This will lint ECMAScript by specifying the `esversion` option. It's best practice for a developer to use a `.jshintrc` file on the project root so all developers can share the listing options.

Can I propose the addition of this file to contain the esversion option to allow for better compatibility with users of jshint?

In my project this look like the below, happy to raise a PR if this thought to be a useful addition.
``` bash
cat ./.jshintrc
{
    "esversion": 6
}
```

**Comment by frenzzy** [comment]
Why don't you want to just use [ESLint](https://github.com/eslint/eslint) instead of [JSHint](https://github.com/jshint/jshint)?

http://www.npmtrends.com/jshint-vs-eslint-vs-jslint-vs-babel-eslint-vs-jscs

**Comment by tomharvey** [comment]
Fair point; I'll shift over to that. In that case, is there a need for an `.eshintrc` file or are the defaults the best option for this project?

**Comment by frenzzy** [comment]
ESLint already [configured in this project](https://github.com/kriasoft/react-static-boilerplate/blob/2b73935e12a798367034bd4076e86e199d05a915/package.json#L87-L90) using [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).
You can find style guide here: https://github.com/airbnb/javascript
Feel free to change any rules at your own discretion.

**Comment by tomharvey** [comment]
Thanks
