### ISSUE TITLE
Build > URL direct access not working

### ISSUE THREAD

**Issue by BaptWaels** [kriasoft/react-static-boilerplate#184]
Hi,

I'm unable to direct access URL inside my project after a build. 

## **Reproduce bug:**
$ mkdir MyApp
$ cd MyApp
$ yo react-static
$ npm run build
$ cd public/
$ docker run -p 3000:80 -v "$PWD":/usr/share/nginx/html:ro -d nginx
(Create a static nginx server, easier with docker, you could use apache to serve files if you don't know docker)

## **Working:** 
1 - http://localhost:3000 
2 - Click on About is working and redirects to http://localhost:3000/about 

## **Not working:** 
1 - Try to access directly http://localhost:3000/about returns 404 not found

Is there a way to fix it and being able to access each page directly ?

**Comment by justin22** [comment]
I'm also facing the same issue. But just in production build. In development mode, this works fine.

**Comment by BaptWaels** [comment]
Which is a real problem, I'm not able to access /confirm?token=:token when a new user received a mail to confirm his account. I've made some investigation but still not able to access directly the route.

**Comment by justin22** [comment]
I reproduced this issue. 
Cloned the same project from this repository. 

`npm install` and then `node run build --release`.

Deployed the contents in the `public` directory.

The project is available is [React static boilerplate-Clone](http://newsrush.today).

If clicked on `about` link, it goes to `about` page.
But if `http://newsrush.today/about` is typed on address bar- receives the following error.

**Not Found
The requested URL /about was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.**

@koistya

**Comment by BaptWaels** [comment]
I think I've found a solution [here](https://github.com/davezuko/react-redux-starter-kit/issues/1080#issuecomment-260627825). I  haven't tried it yet.

**Comment by govarthananve** [comment]
@BaptWaels  its working
