### ISSUE TITLE
Mocha unit tests failing

### ISSUE THREAD

**Issue by amkoehler** [kriasoft/react-static-boilerplate#193]
This might not be an issue specific to this project, but I haven't been able to find a solution. When running `npm run test` out of the box, it looks like es6 imports aren't working:

```
$ yarn test
yarn test v0.18.1
$ mocha --compilers js:babel-register
/Users/akoehler/Development/Repos/react-static-boilerplate/test/base.test.js:1
(function (exports, require, module, __filename, __dirname) { import { expect } from 'chai';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
...
...
```

I installed with node v6.9.4. 

**edit:** I was able to get this working by copying the babel configuration in `package.json` to a `.babelrc` file within the `test` directory and removing the `"modules": false` configuration from the "es2015" preset. 

```json
{
  "presets": [
    "react",
    "es2015",
    "stage-1"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

**Comment by rjdestigter** [comment]
+1

**Comment by ericlau-solid** [comment]
I got this working, but as soon as I write a meaningful test, I get a compile error:
```

$ mocha --compilers js:babel-register test/helpers/browser.js test/*.spec.js
C:\Users\ericl\workspace\react-static-boilerplate\components\Avatar\Avatar.js:1
(function (exports, require, module, __filename, __dirname) { import React, { PropTypes } from 'react';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)

```

note that i need to run browser.js to use jsdom for testing react components with enzyme

**Comment by amkoehler** [comment]
@ericlau-solid you're right, the modules issue will still occur when you're testing components that are outside of your test folder. I'm using enzyme too and was able to fix this by moving the `.babelrc` I referenced above to my root directory, so that way it gets used by all files in the project and not just the unit tests. You may need to remove the `"babel"` settings in `package.json` as well to make sure it gets overridden correctly. 

I would still like to know why the `{"modules": false}` setting was added in the first place. I'm guessing it's something to do with webpack 2.

**Comment by koistya** [comment]
@amkoehler `{ "modules": false }` was added in order to allow Webpack 2 do tree-shaking after building the project in release(production, optimized) mode. I just fixed the issue with unit tests (by adding `modules: false` at run-time during compilation of the application bundle (see `tools/webpack.config.js`)

**Comment by amkoehler** [comment]
That should work great. Thanks @koistya!

**Comment by amkoehler** [comment]
Implemented the [fix](https://github.com/kriasoft/react-static-boilerplate/commit/4c8acb54b84feca1fb1e8dab708ba4080f640816) worked for me. If anyone else out there is using Relay and needing to add babelRelayPlugin as a preset, this is what my webpack.config.js looks like:

```
const babelConfig = Object.assign({}, pkg.babel, {
  babelrc: false,
  cacheDirectory: useHMR,
  presets: pkg.babel.presets.map((x) => x === 'latest' ? ['latest', { es2015: { modules: false } }] : x),
});

babelConfig.presets.push({
  plugins: [
    path.resolve(__dirname, 'babelRelayPlugin.js'),
  ],
});
```
