### ISSUE TITLE
Having difficulty getting react carousel libraries to load properly

### ISSUE THREAD

**Issue by ericlau-solid** [kriasoft/react-static-boilerplate#197]
I have tried a number of react carousel npm libraries that require you to load css files from their library. It seems that with this boilerplate css from node_modules don't seem to load properly. Another with successÉ

**Comment by ericlau-solid** [comment]
I figured it out. Webpack settings for loading /node_module css files need to be different than custom css.

**Comment by wideberg** [comment]
Hi, could you please describe how the settings need to differ? I'm having the same problem with slider components.

**Comment by wideberg** [comment]
Solved it by disabling CSS modules completely for css-files in node_modules.
