### ISSUE TITLE
deployment to s3 - Tasks is not defined

### ISSUE THREAD

**Issue by mokkrb** [kriasoft/react-static-boilerplate#200]
Hi, I found your script to deploy a react app to s3.
I followed it, copied the script to run.js, but I am running into this issue:

ReferenceError: tasks is not defined
    at Object.<anonymous> (/Users/me/Repo/repo/subrepor/run.js:1:63)

Any ideas ??

**Comment by kbrooks** [comment]
see https://github.com/kriasoft/react-static-boilerplate/issues/195#issuecomment-276237810
