### ISSUE TITLE
Prevent Layout/Header from unmounting when page changes

### ISSUE THREAD

**Issue by idrm** [kriasoft/react-static-boilerplate#226]
At the moment, whenever the user navigates to a different page the entire `Layout` component (including the `Header` inside it) re-mounts. 

It would be useful to, instead, only remount the `div.content` part of the `Layout` component. For example, when a transition from an expanded to a collapsed state of the `Header` is required.

Can this be accomplished with a quick tweak of the configuration/code somewhere, or would a more extensive re-write be required?

**Comment by frenzzy** [comment]
Take a look at https://github.com/kriasoft/react-starter-kit/pull/959

**Comment by idrm** [comment]
Thanks for the tip!

I understand the issue now -- each page's component (the corresponding `index.js` component) holds a `Layout` inside it, as opposed to the `Layout` holding the page component inside (i.e. the render is `<index.js><Layout>{...page content...}</Layout></index.js>` instead of, say, `<Layout><index.js>{...page content...}</index.js></Layout>`), which causes the re-mount of `Layout` since it's mounted inside a different `index.js` component for each page.
