### ISSUE TITLE
Include in CSS page (import 'style.css')

### ISSUE THREAD

**Issue by ahmetozalp** [kriasoft/react-static-boilerplate#232]
I want to import css work all over the page i have 1 css page but i could not do it somehow help?

example.

components/Layout/Layaut.js

import 'style.css';

style.css file.

body{}
head{}

vs vs...

(sorry bad english have)

**Comment by mksarge** [comment]
This project uses [CSS Modules](https://github.com/css-modules/css-modules) with webpack, so you can import your styles like this:

```js
/* Layout.js */
import css from 'Layout.css';

class Layout extends React.Component {

  ...

  render() {
    return (
      <div className={css.body}>
      ...
      </div>
    )
  }
}
```

```css
/* Layout.css */
.body {
  ...
}

.head {
 ...
}
```

**Comment by ahmetozalp** [comment]
Thank you for the answer.But I would like to call a css running this way not everywhere

example

import  'Layout.css';

class Layout extends React.Component {

  ...

  render() {
    return (
      <div className='testclass'>
      ...
      </div>
    )
  }
}



/* Layout.css */
.testclass {
  ...
}

**Comment by mksarge** [comment]
Try this:

```js
import('!style-loader!css-loader!./Layout.css');

class Layout extends React.Component {
  ...
}
```

**Comment by ahmetozalp** [comment]
Thank You bro :)
