### ISSUE TITLE
relay support

### ISSUE THREAD

**Issue by webmobiles** [kriasoft/react-static-boilerplate#237]
are there plans to support relay to operate graphql ?

**Comment by koistya** [comment]
Relay support is coming within the next two days.

**Comment by koistya** [comment]
@webmobiles I have pushed an early preview of the Relay Modern integration onto the `master` branch. Will commit a few improvements/fixes later on.

You can find Relay configuration in `src/relay.js`. With Relay it makes sense to put your root GraphQL queries at the routing level, see `src/router.js`. The top-level component must wrap everything into Relay's `<QueryRenderer>`. The current implementation starts downloading missing application chunks and fetching GraphQL API simultaneously and once both these promises are resolved, it renders the page, for this purpose a delayed renderer is used, see `src/App/AppRenderer.js`.

So, what do you think? Please, share your opinion.
