### ISSUE TITLE
Documentation has been removed?

### ISSUE THREAD

**Issue by adamp-jomedia** [kriasoft/react-static-boilerplate#257]
/docs/recipes/ no longer exists. Is there an alternative place to see documentation?

**Comment by koistya** [comment]
The boilerplate is now based on `create-react-app` that handles build/test infrastructure and has a massive "[user guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md)" :) In addition to that, it would be great to list some reference articles and blogs posts in README.md file, for example:

#### Reference Articles and Tutorials

* [Using Create React App with Relay Modern](https://hackernoon.com/using-create-react-app-with-relay-modern-989c078fa892)

**Comment by adamp-jomedia** [comment]
Thank @koistya, that's understandable.
