### ISSUE TITLE
Pre-render critical CSS on build to deal with FOUC

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-static-boilerplate#28]
https://en.wikipedia.org/wiki/Flash_of_unstyled_content

**Comment by kevinsimper** [comment]
What is FOUC?

**Comment by dsernst** [comment]
What do we need to fix this? It looks like none of the styles get rendered in the server-side static assets.

**Comment by koistya** [comment]
Wouldn't it be nice to start downloading JavaScript bundle asynchronously even before the HTML page is fully loaded, if so, the HTML page should contain critical CSS for the generated HTML markup:

```html
<html>
  <head>
    <title>Page Title</title>
    <script async src="/bundle.js"></script>
    <style type="text/css">
      /* pre-rendered critical CSS (only styles needed to render the markup below) */
    </style>
  </head>
  <body>
    <div id="root">
      <!-- pre-rendered HTML markup -->
    </div>
  </body>
</html>

```

**Comment by dsernst** [comment]
Makes sense. Do you have a plan of attack in mind already?

**Comment by koistya** [comment]
One way to generate that critical CSS is by using [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader) instead of Webpack's `style-loader`.

**Comment by koistya** [comment]
Closing this issue for now as currently the app operates as a regular [single-page app](https://en.wikipedia.org/wiki/Single-page_application), there is no FOUC, see the demo:

https://rsb.kriasfot.com
