### ISSUE TITLE
CSS not included if JS disabled

### ISSUE THREAD

**Issue by heeton** [kriasoft/react-static-boilerplate#34]
View the site without javascript and there are no styles.

**Comment by weisjohn** [comment]
:+1:

**Comment by weisjohn** [comment]
@heeton see the PR here: https://github.com/koistya/react-static-boilerplate/pull/41

**Comment by koistya** [comment]
I'm not sure if making a website / app work without JavaScript is a practical way to go. It may add lots of complexity to your app.

Feel free to vote up this issue, if you think that making the app work without JS enabled is important.
