### ISSUE TITLE
markup being generated is different on the client or server warning

### ISSUE THREAD

**Issue by reedho** [kriasoft/react-static-boilerplate#37]
Running fresh project generated from version 0.2.9, then open http://localhost:3000/blog give warning: 

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) =".23cjq30ov7k.1.0">Not Found</h1><p dat
 (server) =".23cjq30ov7k.1.0">Blog</h1><p data-rea

The browser rendering http://localhost:3000/404 instead of the pages/blog/index.js.

**Comment by WillemLabu** [comment]
:+1:

**Comment by WillemLabu** [comment]
It seems that the `/blog/` (note the trailing slash) route is not being resolved.
Logging the `lines` constant in `routes-loader.js` gives the following:

```
[
  '  \'/404\': () => require(\'./pages/404.js\'),',
  '  \'/500\': () => require(\'./pages/500.js\'),',
  '  \'/about\': () => new Promise(resolve => require([\'./pages/about.js\'], resolve)),',
  '  \'/blog\': () => new Promise(resolve => require([\'./pages/blog/index.js\'], resolve)),',
  '  \'/blog/test-article-one\': () => new Promise(resolve => require([\'./pages/blog/test-article-one.js\'], resolve)),',
  '  \'/blog/test-article-two\': () => new Promise(resolve => require([\'./pages/blog/test-article-two.js\'], resolve)),',
  '  \'/\': () => new Promise(resolve => require([\'./pages/index.js\'], resolve)),'
]
```

This seems to create a route to `/blog`, but not `/blog/`, which browsers use for directories.
I'll try and find a solution and send a PR, perhaps.

**Comment by koistya** [comment]
This issue is no longer relevant. Will close for now.
