### ISSUE TITLE
building becomes very slow when project gets large

### ISSUE THREAD

**Issue by JianGuo222** [kriasoft/react-static-boilerplate#47]
is there any way to improve the building speed?

it takes me 12 seconds on average to build a single small change every time I try to save it.

and if I save twice, it'll build twice and take twice as long to build, so around 24 seconds.

**Comment by dvdplm** [comment]
You might want to turn caching on in the webpack config; made a big difference for us.

**Comment by JianGuo222** [comment]
thanks, David, that worked for me as well, now the rebuild speed is around 1 second!!

**Comment by dvdplm** [comment]
Indeed, same here!

@koistya perhaps caching could be on by default?

**Comment by dsernst** [comment]
What's the diff look like to turn on caching?

**Comment by koistya** [comment]
Caching is turned on by default in watch mode, when you run the app with `node run` (or `npm start`). In addition to that, I just added caching for `babel-loader` when you run your app with HMR mode (`node run` or `npm star`).

Pro tip: you can also test your app without HMR by running `node run --no-hmr`, or you can test you app in release mode (optimized for deployment) by running `node run --release`.
