### ISSUE TITLE
how can I do wildcard routing

### ISSUE THREAD

**Issue by JianGuo222** [kriasoft/react-static-boilerplate#52]
The routes-loader works well until I'm trying to do wildcard routing like this:
/item/:itemID/:itemCategory

any suggestion how to achieve the SEO friendly wildcard routing?

**Comment by JianGuo222** [comment]
I did something like this in app.js

  let handler;
  
  if (path.indexOf('/item/') === 0) {
    handler = routes['/item'];
  } else {
    handler = routes[path] || routes['/404'];
  }
  const component = await handler();



is there a better solution?

**Comment by JianGuo222** [comment]
but the problem now is loading this url directly:
/item/2321/category

it returns 404.


it works fine if open this url from homepage or /item page.

**Comment by dsernst** [comment]
Yes, this is a very good question. One answer is to use [react-router](https://github.com/rackt/react-router). It would be nice if there was a straightforward way to do this in the existing routing system, though.

**Comment by mmintel** [comment]
This issue is already 5 months old but I hope somebody is willing to help us.. I am also interested in a good solution.

**Comment by koistya** [comment]
The route URLs are handled by [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp), does it handled the wildcard patterns that you're looking for? Here is example (see [`routes.json`](routes.json)):
```json
  {
    "path": "/tasks/:status(pending|completed)?",
    "page": "./pages/tasks",
    "fetch": { "tasks": "GET /api/tasks?status=$status" }
  }
```

**Comment by koistya** [comment]
Here is the doc explaining how the routing works:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/routing-and-navigation.md

Feel free to re-open this issue, if it doesn't cover your use case.
