### ISSUE TITLE
Routing doesn't work for github project pages

### ISSUE THREAD

**Issue by aarjithn** [kriasoft/react-static-boilerplate#58]
Html.js and routes-loader.js is set to load files based on root '/'. A github project page is of the format username.github.io/project and root here is username.github.io. The page content and styling doesnt load as the app.js request is going to username.github.io/app.js. 

I changed the Html.js script src from "/app.js" to "app.js" and the application loads now, but all pages goes to 404 as the route doesn't match. Whereas it should be username.github.io/project/about, the route is set to username.github.io/about. 

This works fine in localhost as about is based on root path (localhost:3000/about). Any idea how to make it work in both localhost as well as the project page? Thanks.

**Comment by katebascombe** [comment]
I'm also having trouble with this issue.

**Comment by timrnz** [comment]
I would recommend `not` using Github pages at all and instead using a free tool similar to [Surge.sh](https://surge.sh). There are [articles dedicated](http://gh-pages-vs.surge.sh/) to how hard it is to deal with GHPages.

It's easy to add an NPM script to do what you want to do once you've installed surge

`npm install -g surge`

In package.json
```js
"scripts": {
  "deploy": "npm build && surge -p build --domain yourdomain.surge.sh"
}
```

Then run `npm deploy` to deploy up to your site. Alternatively attach to a [Travis-CI](https://travis-ci.com/) instance to deploy to surge on your behalf on commit of your code to github.

Hope that helps.

**Comment by aarjithn** [comment]
Thanks for mention of surge, seems to be interesting!

However,  I don't fully agree with the article. The article assumes you don't even have a github account setup, and just want to publish a site without a git repository even. When your code is already in github, its very straightforward to publish to gh-pages. There is an npm-package for gh-pages, and if you have to do is 'gulp deploy'. 

Github pages is a very common publishing platform, so supporting it would be nice to have. Also note that not only github pages, anywhere the static site is hosted outside root would face this issue.

I've managed to get it working - but its not a clean solution. The routes are loaded via `routes-loader.js` in tools, and I had to push list of relative paths into variable `lines`.

**Comment by aarjithn** [comment]
Infact, Deployment to Github pages are mentioned in many places in the readme.md, and even there is a built in script to deploy to branch gh-pages. So sort of misleading if it breaks in Github pages.

`✓ Easy deployment to GitHub Pages, Amazon S3 or Firebase`
`npm run deploy                # Deploys the project to GitHub Pages`

**Comment by timrnz** [comment]
@aarjithn The docs do indeed say easy deployment, they don't say it necessarily works well however.

That said. It's up to @koistya to make the decision on fixes / proper GH Pages support, I was simply offering a simple, reasonable and importantly, free alternative.

> Also note that not only github pages, anywhere the static site is hosted outside root would face this issue

Yes, this is correct but IIRC GHPages is the only alternative that forces you outside of the root. The other solutions such as surge do not. If you're operating outside of the root in that case, you could always simplify by moving all your pages into a `/project` folder. Which, come to think of it could be a deploy only step for GHpages which would solve your routing issues there as well.

**Comment by katebascombe** [comment]
@aarjithn Could you please share the solution you have working in routes-loader.js?

**Comment by aarjithn** [comment]
@katebascombe As I mentioned, its not a solution, just a hack I tried for identifying the issue. It loaded fine, but I was not comfortable in using this, so used another react boilerplate.

Basically I added a copy of routes with the prefix as well (/myproject) and pushed it to lines variable. Rootpath is still needed for localhost routing. 

```javascript
    var ghpages = files.map(file => {
      let path = '/' + file;

      if (path === '/index.js' || path === '/index.jsx') {
        path = '/';
      } else if (path.endsWith('/index.js')) {
        path = path.substr(0, path.length - 9);
      } else if (path.endsWith('/index.jsx')) {
        path = path.substr(0, path.length - 10);
      } else if (path.endsWith('.js')) {
        path = path.substr(0, path.length - 3);
      } else if (path.endsWith('.jsx')) {
        path = path.substr(0, path.length - 4);
      }

      if (target === 'node' || path === '/404' || path === '/500') {
        return `  '/myproject${path}': () => require('./pages/${file}')`;
      }

      return `  '/myproject${path}': () => new Promise(resolve => require(['./pages/${file}'], resolve))`;
  });

    lines.push(ghpages);
```

This goes between 
```javascript
var lines = files.map(file => {
...
});

//here

if (lines.length) {
```

As you can see a bad idea for actual use because of the hardcoded project name as prefix to path. I tried the obvious solution to remove the leading '/' but it didn't work somehow. Just play around this, and you should get it working. Don't forget to update script src in Html.js from /app.js to app.js. Let me know how it turned out!

**Comment by katebascombe** [comment]
Thanks for sharing. My project is just a throwaway prototype due tomorrow so any solution is a good solution :-D

I ended up trying out surge.sh and it was really easy to get up and running in just a few minutes.

**Comment by dsernst** [comment]
As another option, if you name your github repo `username.github.io`, it will load the ghpages at that root, or you can CNAME it to a custom domain.

**Comment by piotryordanov** [comment]
@timrnz kudos for sharing surge.hs it does the job <3

**Comment by koistya** [comment]
The current recommended approach is to use Firebase, it allows to rewrite all unknown URLs to the `/index.html` page, that works great with singe-page apps. Here is the doc explaining how the routing works in this project temlate:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/routing-and-navigation.md

You may also want to check documentation to the `path-to-regexp` and `history` npm modules, for example, the later one has `baseUrl` configuration option that helps with this scenario when the app is hosted in a sub-folder.

**Comment by guilhermedecampo** [comment]
Surge is love ❤️ 

https://surge.sh/help/adding-a-200-page-for-client-side-routing

**Comment by koistya** [comment]
@guilhermedecampo are there any advantages of using Surge over Firebase? It's hard to beat Firebase pricing - Free for a site including custom domain with SSL.

**Comment by guilhermedecampo** [comment]
@koistya just a matter of choice indeed. Both offer the same features. 
Everything rots but we never know what the guys at google want to do with their acquisitions.
