### ISSUE TITLE
How does the routing work?

### ISSUE THREAD

**Issue by lulato** [kriasoft/react-static-boilerplate#6]
Could you explain a bit more how routing works in your application?

--- [other tasks](https://waffle.io/koistya/react-static-boilerplate) ---

**Comment by Metis77** [comment]
+1

**Comment by koistya** [comment]
Inside the `app.js` file there is a list of routes in a form of a plain JavaScript object:

```js
const routes = {};
```

During a build it is filled with routes based on the list of `*.js` files in the `src` folder. So that if you have `/src/about.js` and `/src/404.js` it will generate the following routes:

```js
const routes = {
  '/404', () => new Promise(resolve => require(['./404.js'], resolve),
  '/about', () => new Promise(resolve => require(['./about.js'], resolve)
};
```

It uses webpack's [code splitting](https://github.com/webpack/docs/wiki/code-splitting) feature to load missing components at run-time.

Then, when application loads into a browser, it extracts a route handler from that object given a URL path and executes it:

```
const action = routes[window.location.pathname] || routes['/404'];
const component = await action();
React.render(React.createElement(component), document.body);
```

Hope this helps :)

**Comment by koistya** [comment]
[![image](https://cloud.githubusercontent.com/assets/197134/8962885/ba2b472c-3625-11e5-9da6-16aed20146d5.png)](https://twitter.com/koistya/status/609762956646219776)

**Comment by westn** [comment]
How does the navigation-link look like?
Is it so that I can navigate to "http://localhost:3000/#about" or "http://localhost:3000/about", I can't seem to get any of them to work.

**Comment by koistya** [comment]
When you a regular navigation link such as `<a href="/about">About</a>` this links needs to have a click handler which redirects a client to a new page without full page refresh and prevents the default behaviour (`event.preventDefault()`). I will try to create an example how you can do it..

**Comment by Metis77** [comment]
I'd love to have an tutorial, too.

**Comment by philkeys** [comment]
@koistya 

With this routing system, is there a way to have a route, when activated, put the user at the top of the page? I've found that if I click on a link halfway down a screen, then the new view has the same placement.

Any help would be greatly appreciated.

**Comment by vineesv** [comment]
The routes do not work if the compiled/build folder is made to run on a non-nodeJS based server like Apache or WAMP. Only the page at the root '/'  loads in a non-node serve. Is there a node server dependency for the routes to work?
Could you advice on how to fix this to make the routes work on a non node server?

**Comment by koistya** [comment]
@vineesv you may want to change the `pages` build step, so that it generates `index.html` for each route. E.g. instead of `/about.html` you need to have `/about/index.html`.

**Comment by ohNegative** [comment]
@philkeys have you tried this yet: https://www.npmjs.com/package/react-scroll

**Comment by ohNegative** [comment]
@koistya quick question: the folder structure is obvious, but I can't seem to get the router to go to the blog index page: http://localhost:3000/blog/ or http://localhost:3000/blog/index but the router is working fine for the two article pages: http://localhost:3000/blog/test-article-one

Is there something I'm missing? 

Thanks,

P

**Comment by koistya** [comment]
It seems like BrowserSync doesn't understand that '/blog/index.html' should be accessed via '/blog' URL. I guess, it might be a good idea to generate /blog.html instead of /blog/index.html inside the build (dist) folder.

**Comment by koistya** [comment]
Here is the logic that generates .html file names from React routes:

https://github.com/koistya/react-static-boilerplate/blob/master/tools/lib/routes-loader.js

**Comment by ohNegative** [comment]
@koistya thanks for the heads up - I'll try that!

**Comment by n8sabes** [comment]
We need to locate the root of the site one level below the domain name, however the compilation process crashes when you include a path in routes-loader. We need:

http://domainn.com/v1/index.html

How can this be done?

**Comment by koistya** [comment]
@n8sabes I have refactored the routing, do you think it covers your use case? Check it out:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/routing-and-navigation.md

If not, please don't hesitate to contact me with some more info about your scenario.
