### ISSUE TITLE
Support SCSS @mixin

### ISSUE THREAD

**Issue by n8sabes** [kriasoft/react-static-boilerplate#69]
SCSS @mixin classes are not supported in current build process. I've added support by using sass-loader.

Here is how I resolved the issue:
1. npm i -D sass-loader
2. In webpack.config.js, replace all instances of 'postcss-loader' with 'sass-loader'

If there is a better way to achieve this, please let me know.

**Comment by frenzzy** [comment]
Or alternatively `postcss-loader` => `postcss-loader?parser=postcss-scss` [here](https://github.com/koistya/react-static-boilerplate/blob/d1701d7aa5b618bb5c2d28e6883bf3b95ec99acc/tools/webpack.config.js#L148)

More info: [PostCSS SCSS Syntax](https://github.com/postcss/postcss-scss)

**Comment by n8sabes** [comment]
@frenzzy Seems better to keep with postcss-loader, but can't get your alternate approach work. Did npm install postcss-scss and made following edit:

`loaders: ['style-loader', 'css-loader', 'postcss-loader?parser=postcss-scss'],`

I think postcss-scss needs to be required. I tried adding `require('postcss-scss')(),` before [line 87](https://github.com/koistya/react-static-boilerplate/blob/d1701d7aa5b618bb5c2d28e6883bf3b95ec99acc/tools/webpack.config.js#L87), but no luck.

What am I missing?

**Comment by frenzzy** [comment]
[postcss-scss](https://github.com/postcss/postcss-scss) not needed on line 87, you just need to install it: `npm install postcss-scss`
It's just a parser and mixins processed by [precss](https://github.com/jonathantneal/precss) plugin on line 87 ([see mixins section](https://github.com/jonathantneal/precss#mixins))

It should work directly for the imported/required files into js code:
```js
/* MyComponent.js */
import style from './stylesWithMixins.scss';
// or
require('./stylesWithMixins.scss');
```

For imported styles in the css code you also need to configure [postcss-import](https://github.com/postcss/postcss-import/):
```scss
/* MyComponent.scss */
@import './mixins.scss'; /* processed by postcss-import */
```

**Comment by motleydev** [comment]
This is likely a higher level discussion between going with sass or postcss as a whole. The idea, if I'm not mistaken, is to try and move away from precompiler specific syntax as much as possible and move towards "future CSS" syntax. Either way, I think an official note on this in the docs would be a good thing.

**Comment by koistya** [comment]
Using plain CSS via PostCSS is a recommended approach in RSB, because it reduces the size of the tech stack in your app, enforces you to lean vanilla CSS and modern CSS Level 3 features that allow you doing everything you would normally do with Sass/SCSS, also compilation / bundling will work faster with plain `.css` files and PostCSS pre-processor.

I just have added the doc explaining how to configure Sass in case you still want to use it:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/how-to-use-sass.md

Feel free to add more stuff into this doc if something is missing.

**Comment by poizoncc** [comment]
@koistya please, explain step 3 in more details
