### ISSUE TITLE
Routes Loader Broken?

### ISSUE THREAD

**Issue by n8sabes** [kriasoft/react-static-boilerplate#70]
It appears the `tools/lib/routes-loader.js` is broken and does correctly generate the / route for any given sub-directory unless it's included in the navigation.js file. Everything but index.html in that same sub-directory is correctly generated and accessible.

To reproduce the issue, using a clean git master checkout, navigate to /blog and you'll get a 404 error. Then navigate to /blog/test-article-one and it works fine.

BTW - The browser reports what I believe is a hot-loader warning in the console when you navigate to /blog or any other / sub-directory not included in navigation.js. Deployed builds do not emit this warning, but still the /blog/index.html fails to load and the 404 page is returned.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) =".13ltol7u1vk.1.0">Not Found</h1><p dat
 (server) =".13ltol7u1vk.1.0">Blog</h1></div></div
warning
_mountImageIntoNode
ReactMount__mountImageIntoNode
mountComponentIntoNode
perform
batchedMountComponentIntoNode
perform
batchedUpdates
batchedUpdates
_renderNewRootComponent
ReactMount__renderNewRootComponent
_renderSubtreeIntoContainer
render
React_render
callee$2$0$
tryCatch
invoke
(anonymous function)
invoke
callInvokeWithMethodAndArg
(anonymous function)
initializePromise
Promise
enqueue
(anonymous function)
async
callee$2$0
route$
tryCatch
invoke
(anonymous function)
invoke
invoke
promiseReactionJob
```

**Comment by n8sabes** [comment]
Please see #46 as this appears to be related. @bionikspoon posted a code snippet that seems to work around the issue. Not sure where the best place is to correct the problem and update the project.

```
// # app.js
const route = async(path, callback) => {
  if (path.endsWith('/') && path !== '/') {
    path = path.slice(0, -1);
  }
  const handler = routes[path] || routes['/404'];
  // ...
};
```

**Comment by koistya** [comment]
The routing code from the latest version on master should work fine with the trailing slashes in URLs. Can you check it out please? Also here is the doc explaining how it works:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/routing-and-navigation.md

In combination with [Firebase](https://firebase.google.com) hosting it provides a good alternative to the routing solution used previously in this boilerplate.

Feel free to re-open, if this issues is still current.
