### ISSUE TITLE
Use Kinto as Distributed Database

### ISSUE THREAD

**Issue by zwhitchcox** [kriasoft/react-static-boilerplate#72]
Hey man,

Love the project! Already learning stuff I didn't know by browsing the source code.

Just an idea, but have you thought of adding [kinto](https://kinto.readthedocs.org/en/latest/) as the database? People using github pages for their sites could add a contact form or w/e, without having to create and maintain a server, which is my primary goal.

Just an idea.

Thanks for the great project!

**Comment by koistya** [comment]
Hey, thanks for the suggestion! [Kinto](http://www.kinto-storage.org/) looks really interesting, I like it. As far as i understand it requires installing some server-side service on your server?

RSB is promoting a serverless architecture, where you can plug some existing API provided in a form of SaaS. For example [Firebase](https://firebase.google.com), [Auth0](https://auth0.com), or [Reindex](https://www.reindex.io/).

Have you checked the latest version? It's pre-configured with Firebase hosting (`node run publish`), and might be a good starting point to plug in Firebase or Reindex backend.
