### ISSUE TITLE
Just one entry point?

### ISSUE THREAD

**Issue by AlexYegupov** [kriasoft/react-static-boilerplate#78]
Hello.
Sorry, I didn't find any information if build site has just one entry points. 

for example I can reproduce see unsuccessful scenary:
1) npm run build release
2) run local server in build directory  (cd build; python -m SimpleHTTPServer 3000)
then open "localhost:3000/about" in browser and got 404 error
(if open "localhost:3000" and click "about" link then works fine)

Is that behavour planned? Don't you think that any page of site (especially it it's static) COULD be in real life the entry point (for example if user add some page to his browser bookmarks)?

Thanks.

**Comment by LucaBlackDragon** [comment]
I think this is related to #46

**Comment by koistya** [comment]
I think this issues has been fixed. Run `node run start`, go to `/about` page, hit refresh, the page should reload without any issues.
