### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by Aleyasen** [kriasoft/react-static-boilerplate#95]
May we have a Dockerfile for the project?

Thanks.

**Comment by koistya** [comment]
@Aleyasen can you give an example what would be the valid use case for deploying this static site via Docker as opposed to just pushing it to some static site hosting like GitHub Pages, Firebase Hosting, Amazon S3, etc.?

**Comment by Aleyasen** [comment]
Thanks for the reply @koistya . Maybe I am using it in a wrong way, but in my use case, the boilerplate is a UI for a restful API provider. The restful API provider (and other services) are based on docker, so I thought maybe it's a good idea to have this one also on docker. Does it make sense for you? Also, do you think whether the project is a good fit for our use case or not.

**Comment by koistya** [comment]
@Aleyasen so, it's more like a part of a large web application project containing server-side code? If so, maybe Dockerfile should be in the scope of that parent project? I'm using a similar approach here - [ASP.NET Core Starter Kit](https://github.com/kriasoft/aspnet-starter-kit), where React app is just a UI layer on top of ASP.NET Core server-side app and is being deployed as a part of it.
